# Generated by Django 5.1.3 on 2025-07-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='log_level',
            new_name='level',
        ),
    ]
