# Generated by Django 5.2.4 on 2025-07-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_log_level_logentry_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
