# Generated by Django 5.2.4 on 2025-07-28 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_notofication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notofication',
            new_name='Notification',
        ),
    ]
