# Generated by Django 5.2.4 on 2025-07-29 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_notification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Assign the admin this viewer reports to', limit_choices_to={'profile__role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
