# Generated by Django 5.2.4 on 2025-08-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_logentry_assigned_to_logentry_resolution_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='resolution_note',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='status',
        ),
    ]
