# Generated by Django 5.2.4 on 2025-08-02 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_remove_logentry_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logentry',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20),
        ),
    ]
